# Generated by Django 5.1.1 on 2024-09-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppigcart',
            name='product',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='api.product', verbose_name='Продукт'),
        ),
    ]
