# Generated by Django 5.1.1 on 2024-10-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('products', '0002_alter_product_options_alter_product_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppigcart',
            name='product',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
    ]
