# Generated by Django 5.1.1 on 2024-10-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/large', verbose_name='большое изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(upload_to='product_images/medium', verbose_name='среднее изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/small', verbose_name='маленькое изображение'),
        ),
    ]
